// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions, Firebase;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu16zXcPfbS8893rwIhVFncjLG3nVIeCo',
    appId: '1:33599176949:web:77aa38bceda0e6481185bc',
    messagingSenderId: '33599176949',
    projectId: 'reddit-colne',
    authDomain: 'reddit-colne.firebaseapp.com',
    storageBucket: 'reddit-colne.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdG-UTwJ7mDQOuHdrd0elKbkfr62YYwBE',
    appId: '1:33599176949:android:8ae6caba459dc2781185bc',
    messagingSenderId: '33599176949',
    projectId: 'reddit-colne',
    storageBucket: 'reddit-colne.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqx0MustnGVVYewwaqfqUcfnvRpTDmtnc',
    appId: '1:33599176949:ios:119fdbae52c985461185bc',
    messagingSenderId: '33599176949',
    projectId: 'reddit-colne',
    storageBucket: 'reddit-colne.appspot.com',
    iosClientId: '33599176949-ve6ihve9q8tcni0jmn7hq2ea7kt7kv6i.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}

Future<void> initializeFirebase() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}
